require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExaminersController do

  # This should return the minimal set of attributes required to create a valid
  # Examiner. As you add validations to Examiner, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "datetime" => "2014-01-01 14:05:03" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExaminersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all examiners as @examiners" do
      examiner = Examiner.create! valid_attributes
      get :index, {}, valid_session
      assigns(:examiners).should eq([examiner])
    end
  end

  describe "GET show" do
    it "assigns the requested examiner as @examiner" do
      examiner = Examiner.create! valid_attributes
      get :show, {:id => examiner.to_param}, valid_session
      assigns(:examiner).should eq(examiner)
    end
  end

  describe "GET new" do
    it "assigns a new examiner as @examiner" do
      get :new, {}, valid_session
      assigns(:examiner).should be_a_new(Examiner)
    end
  end

  describe "GET edit" do
    it "assigns the requested examiner as @examiner" do
      examiner = Examiner.create! valid_attributes
      get :edit, {:id => examiner.to_param}, valid_session
      assigns(:examiner).should eq(examiner)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Examiner" do
        expect {
          post :create, {:examiner => valid_attributes}, valid_session
        }.to change(Examiner, :count).by(1)
      end

      it "assigns a newly created examiner as @examiner" do
        post :create, {:examiner => valid_attributes}, valid_session
        assigns(:examiner).should be_a(Examiner)
        assigns(:examiner).should be_persisted
      end

      it "redirects to the created examiner" do
        post :create, {:examiner => valid_attributes}, valid_session
        response.should redirect_to(Examiner.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved examiner as @examiner" do
        # Trigger the behavior that occurs when invalid params are submitted
        Examiner.any_instance.stub(:save).and_return(false)
        post :create, {:examiner => { "datetime" => "invalid value" }}, valid_session
        assigns(:examiner).should be_a_new(Examiner)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Examiner.any_instance.stub(:save).and_return(false)
        post :create, {:examiner => { "datetime" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested examiner" do
        examiner = Examiner.create! valid_attributes
        # Assuming there are no other examiners in the database, this
        # specifies that the Examiner created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Examiner.any_instance.should_receive(:update_attributes).with({ "datetime" => "2014-01-01 14:05:03" })
        put :update, {:id => examiner.to_param, :examiner => { "datetime" => "2014-01-01 14:05:03" }}, valid_session
      end

      it "assigns the requested examiner as @examiner" do
        examiner = Examiner.create! valid_attributes
        put :update, {:id => examiner.to_param, :examiner => valid_attributes}, valid_session
        assigns(:examiner).should eq(examiner)
      end

      it "redirects to the examiner" do
        examiner = Examiner.create! valid_attributes
        put :update, {:id => examiner.to_param, :examiner => valid_attributes}, valid_session
        response.should redirect_to(examiner)
      end
    end

    describe "with invalid params" do
      it "assigns the examiner as @examiner" do
        examiner = Examiner.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Examiner.any_instance.stub(:save).and_return(false)
        put :update, {:id => examiner.to_param, :examiner => { "datetime" => "invalid value" }}, valid_session
        assigns(:examiner).should eq(examiner)
      end

      it "re-renders the 'edit' template" do
        examiner = Examiner.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Examiner.any_instance.stub(:save).and_return(false)
        put :update, {:id => examiner.to_param, :examiner => { "datetime" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested examiner" do
      examiner = Examiner.create! valid_attributes
      expect {
        delete :destroy, {:id => examiner.to_param}, valid_session
      }.to change(Examiner, :count).by(-1)
    end

    it "redirects to the examiners list" do
      examiner = Examiner.create! valid_attributes
      delete :destroy, {:id => examiner.to_param}, valid_session
      response.should redirect_to(examiners_url)
    end
  end

end
